### ISSUE TITLE
initial coef and predict value

### ISSUE THREAD

**Issue by kiminh** [VinceShieh/spark-ffm#1]
Thanks for your spark implementation of FFM.
Here's my question:
generateInitWeights() ... val coef = 0.5 / Math.sqrt(param.k) ...
predict()  ... val v: Double = 2.0 * v1 * v2 * r ...

Why not 
generateInitWeights() ... val coef = 1.0 / Math.sqrt(param.k) ...
predict()  ... val v: Double = 1.0 * v1 * v2 * r ...

This is more close to the description in original Paper,"The initial values of w are randomly sampled from a uniform distribution between [0,1.0/sqrt(k)]"

**Comment by VinceShieh** [comment]
Yes, you are right. The reason behind this change is actually, we found that generateInitialWeight with smaller initial coefficients gave us 1% up in terms of accuracy when we used it in our case. I believe it's just related to my dataset, so I will change it back. Thanks for your comments :)
