### ISSUE TITLE
Prediction Label >= 0.5 should change to > 0.5 ？

### ISSUE THREAD

**Issue by Thinkgamer** [VinceShieh/spark-ffm#18]
In TestFFM.scala
val scores: RDD[(Double, Double)] = testing.map(x => {
      val p = ffm.predict(x._2)
      val ret = if (p >= 0.5) 1.0 else -1.0
      (ret, x._1)
    })
should change to 
val scores: RDD[(Double, Double)] = testing.map(x => {
      val p = ffm.predict(x._2)
      val ret = if (p > 0.5) 1.0 else -1.0
      (ret, x._1)
    })

because In Spark source code（BinaryLabelCounter.scala）is

/** Processes a label. */
  def +=(label: Double): BinaryLabelCounter = {
    // Though we assume 1.0 for positive and 0.0 for negative, the following check will handle
    // -1.0 for negative as well.
    if (label > 0.5) numPositives += 1L else numNegatives += 1L
    this
  }

**Comment by VinceShieh** [comment]
actually, 'p' in TestFFM and 'label' in BinaryLabelCounter are not the same. In TestFFM, "p" is the probability return from FFM inference to set the label, which is the same 'label' in BinaryLabelCounter. 
Thanks for the comment.
