### ISSUE TITLE
tr_loss is always NaN

### ISSUE THREAD

**Issue by WeiyueSu** [VinceShieh/spark-ffm#7]
Hi, Nice code! I try to run this code on my dataset, but the tr_loss is always NaN. I found a part of weights is NaN too. Are there any possible reason for it?

**Comment by VinceShieh** [comment]
we've received same feedbacks from other users but were told it's their dataset issue. can you share your dataset so that we can look into it when we are available?

**Comment by WeiyueSu** [comment]
Yeah, I just sent the smallest version of my dataset to your mail. I have train the original libffm on my dataset and everything work well.

**Comment by VinceShieh** [comment]
SparkFFM was implemented based on original FFM paper, but technically we wouldn't compare SparkFFM with libFFM, since during each iteration, the data they are dealing with is different, SparkFFM deals with a portion of the data to compute gradient etc. while libffm uses the whole dataset,  it's possible to get NaN value from a partial dataset.
We will look into it.

**Comment by WeiyueSu** [comment]
I do some test just now and it seem that overflow happen. At the first iteration, if the predict value is about 800 and the label is -1, the expnyt become NaN, then everything goes wrong.

**Comment by WeiyueSu** [comment]
BTW, I didn't understand using a portion of the data. Did you mean they compute gradient in each partition? It truly different from the libffm. Or something like miniBatchFraction in spark mllib? In my situation, the whole dataset cannot load in memory one-time(always happen) although I am using a cluster. I think miniBatchFraction is a significant function.

**Comment by VinceShieh** [comment]
Yes, unlike libFFM, SparkFFM computes gradient with partitions of the dataset. Currently, I'm quite occupied, will try to look at it sometime this week or next week. Thanks.

**Comment by lmxiaonuo** [comment]
same problem when the train set is large

**Comment by VinceShieh** [comment]
please do a quick check on https://github.com/Intel-bigdata/imllib-spark to see whether the problem exists.
meanwhile, please check your dataset, whether there are features with huge scale comparing to the others.
Thanks!

**Comment by VinceShieh** [comment]
reopen the issue if the problem exists. Thanks.
