### ISSUE TITLE
Feature indices do not conincide

### ISSUE THREAD

**Issue by xiaoxuqi-ms** [VinceShieh/spark-ffm#9]
As per the weights array, feature index should coincide with each. 
Let's say a feature j1 = data(i)._2 - 1 gets its weight for field f2 as following: j1 * align1 + f2 * align0
For FFMModel in FieldAwaredFactorizationMachine.scala, line 122 and line 131,  index for datai is data(i)_2 -1, however, for dataii is data(ii). Should these conform with each other?
val j1 = data(i)._2 - 1  [line 122]
      val f1 = data(i)._1
      val v1 = data(i)._3
......
        while (ii < valueSize) {
          val j2 = data(ii)._2 [line 131]
          val f2 = data(ii)._1
        ......

**Comment by Ricky-WL** [comment]
I have found the same question.
![ffm_question](https://user-images.githubusercontent.com/814343/34351121-a0561aa2-ea55-11e7-80cf-2b675344be8f.png)

**Comment by VinceShieh** [comment]
guys, sorry for late reply. it seems vague to me now, but I think you are right. The reason behind is the feature index is [0, n-1], and I made a guard on j2 that's why the problem didnt expose.
 Can you guys submit a PR to fix this issue? If not, I will fix it sometime later. :)
Thanks

**Comment by xiaoxuqi-ms** [comment]
And I think this should also be fixed in intel mllib.

**Comment by VinceShieh** [comment]
thanks. please make sure that you've built and tested the PR. :)

**Comment by xiaoxuqi-ms** [comment]
Yes, PR is tested

**Comment by Ricky-WL** [comment]
Thank you for reply and fixing this issue.

**Comment by Ricky-WL** [comment]
One more question:
in a9a_ffm ,  all index start from 1, need it minus one when load the data in TestFFM.scala?

**Comment by xiaoxuqi-ms** [comment]
I donot think it's necessary though.
